version: '1.0'

services: 

  back:    
    env_file:
    -  ./backend/.env  
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: shoppingcart-back
    container_name: shoppingcart-back
    ports:
      - 8001:8002
    networks:
      - localwhat
  front:
    env_file:
    -  ./frontend/.env 
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: shoppingcart-front
    stdin_open: true
    container_name: shoppingcart-front
    ports:
      - 3000:8080
    networks:
      - localwhat
networks:
  localwhat: